packages:
  - packages/*
  - packages/use-cases/*
  - packages/functional-core/*
  - packages/components/*
  - apps/*
  - examples/

# ignoredBuiltDependencies:
#   - electron
#   - esbuild
onlyBuiltDependencies:
  - electron
  - esbuild
  - "@esbuild/*"
  - better-sqlite3
