packages:
  - packages/*
  - packages/app-services/*
  - apps/*
  - examples/

# ignoredBuiltDependencies:
#   - electron
#   - esbuild
onlyBuiltDependencies:
  - electron
  - esbuild
  - "@esbuild/*"
